---
# Install java packages on debian based distributions.

- name: Install openjdk repo.
  apt_repository:
    repo: "ppa:openjdk-r/ppa"

- name: Install the openjdk 1.8 package.
  apt:
    name: "{{ java_packages_packagename }}{{ java_packages_headless }}"
    state: latest
    update_cache: yes
    install_recommends: no