---
# Install java packages on redhat based distributions.

- name: Install EPEL.
  yum: name=epel-release state=present

- name: Install the openjdk 1.8 package.
  yum:
    name: "{{ java_packages_packagename }}{{ java_packages_headless }}.x86_64"
    state: installed

